package com.nus.cubic;

/**
 * Created by duy on 1/2/15.
 */

import com.nus.LmSumSquaresError;
import com.nus.LmSolver;

/**
 * Task: Suppose the true model is f(x) = -x^3 + 2 * x^2 - 3 * x + 4
 *
 * Given the set of points generated by f(x) = -x^3 + 2 * x^2 - 3 * x + 4 with
 * some noise, use Levenberg-Marquardt algorithm to find the model to fit
 * all the points.
 */
public class Main {
  public static void main(String[] args) {
    double[][] xy = {
      {0.0, 4.2}, {1.0, 1.99}, {1.5, 0.627f}, {-2, 26.02}, {3, -14.02},
      {4.0, -40.0}, {3.5, -24.87}, {-0.5, 6.125}, {-1, 9.99999}
    };

    int numData = xy.length;
    double x[] = new double[numData];
    double y[] = new double[numData];
    for (int i = 0; i < numData; ++i) {
      x[i] = xy[i][0];
      y[i] = xy[i][1];
    }

    ModelCubicFunc model = new ModelCubicFunc(x, y);
    LmSumSquaresError errorFunc = new LmSumSquaresError(model);

    LmSolver lmSolver = new LmSolver(errorFunc, 1e-3, 50, 1e-8, 1e-8);

    double abc[] = {8, -10, 4, 5};
    lmSolver.solve(abc);

    System.out.println("Result:");
    System.out.println(abc[0]);
    System.out.println(abc[1]);
    System.out.println(abc[2]);
    System.out.println(abc[3]);
  }
}
